### ISSUE TITLE
회색 명칭이 통일되지 않는 문제 

### ISSUE THREAD

**Issue by eungyeole** [semicolondsm/SemicolonDesign_Android#4]
해당 부분에서 그레이 색깔의 명칭이 grey와 gray로 나눠지는 문제를 발견했습니다
gray로 통일 부탁드립니다.

https://github.com/semicolonDSM/SemicolonDesign_Android/blob/64d5811c85cf0b8813c06b0160475bf8401e8179/app/src/main/java/com/semicolon/semicolondesign/colors/primary/grey/GrayColor.kt#L1-L29

**Comment by shw0471** [comment]
@jaewonkim1468 님이 고쳤습니다
